### ISSUE TITLE
Helper script not working on windows

### ISSUE THREAD

**Issue by jimmyMisa** [RivoLink/opencc#1]
I got this error when installing in windows

![image](https://github.com/RivoLink/opencc/assets/16359487/b79c975c-2382-4885-b734-493c512d8ab9)

Did a quick fix

```
.helper\scripts\token.php
$dir = substr(__DIR__, 0, strpos(__DIR__, '/.helper'));
to
$dir = substr(__DIR__, 0, strpos(__DIR__, '\.helper'));
```

**Comment by RivoLink** [comment]
Thank you for your notification and contribution

This bug was fixed on pull request [#2](https://github.com/RivoLink/opencc/pull/2)
